version: '3.8'

services:
  # این بخش را کامنت کردیم تا از تداخل با Neon جلوگیری شود
  # postgres:
  #   image: postgres:15
  #   restart: always
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: pidao
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - pi_network

  backend:
    build: ./backend
    restart: always
    env_file: ./backend/.env
    # بک‌اِند مستقیماً از طریق DATABASE_URL به Neon وصل می‌شود
    networks:
      - pi_network

  frontend:
    build: ./frontend
    restart: always
    env_file: ./frontend/.env
    depends_on:
      - backend
    networks:
      - pi_network

  reverse-proxy:
    build: ./reverse-proxy
    restart: always
    environment:
      - DOMAIN_NAME=apppidaonkm2562.pinet.com
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    networks:
      - pi_network

networks:
  pi_network:
    driver: bridge
